# Generated by Django 5.2.2 on 2025-08-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hilo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='hilos', to='main.tag'),
        ),
    ]
