# Generated by Django 5.2.5 on 2025-08-13 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_noticia_comentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='likes',
        ),
        migrations.AddField(
            model_name='noticia',
            name='usuarios_dislike',
            field=models.ManyToManyField(blank=True, related_name='noticias_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticia',
            name='usuarios_like',
            field=models.ManyToManyField(blank=True, related_name='noticias_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
