# Generated by Django 5.2.5 on 2025-08-13 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_noticia_dislikes_remove_noticia_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='usuarios_like',
            field=models.ManyToManyField(blank=True, related_name='comentarios_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
