# Generated by Django 5.2.5 on 2025-08-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comentario_usuarios_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='noticia',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
