# Generated by Django 5.2.5 on 2025-08-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_noticia_dislikes_noticia_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='likes',
        ),
    ]
